name: '✨ Feature Request'
description: Suggest a new feature or enhancement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!

        Please check if a similar feature request already exists:
        - [Open Issues](https://github.com/0xstern/tailwind-theme-extractor/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement)

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Describe the problem this feature would solve.
      placeholder: |
        I'm always frustrated when...
        This would be useful for...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your ideal solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other solutions or workarounds you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information, examples, or use cases.
